[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts", "@solmate=lib/solmate/src"]

solc_version = "0.8.19"

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# 合约字节码大小限制 EIP-170: 24576 bytes，开启优化器可以减小字节码大小
optimizer = true
optimizer_runs = 200